### ISSUE TITLE
[Investigation] Can we choose `PYTHONUTF8=1` behavior to be the default on windows?

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/relative-environment-for-python#49]
Can we choose `PYTHONUTF8=1` behavior to be the default on windows? This is when building python.

https://docs.python.org/3/using/windows.html#utf-8-mode

**Comment by dwoz** [comment]
Setting this environment via python code doesn't seem to have any affect.

```
PS C:\Users\dan\relative-environment-for-python> meh\Scripts\python.exe
Python 3.10.9 (main, Feb 13 2023, 16:27:34) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, locale
>>> os.environ["PYTHONUTF8"] = "1"
>>> locale.getpreferredencoding()
'cp1252'
```

**Comment by s0undt3ch** [comment]
> Setting this environment via python code doesn't seem to have any affect.
> 
> ```
> PS C:\Users\dan\relative-environment-for-python> meh\Scripts\python.exe
> Python 3.10.9 (main, Feb 13 2023, 16:27:34) [MSC v.1934 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import os, locale
> >>> os.environ["PYTHONUTF8"] = "1"
> >>> locale.getpreferredencoding()
> 'cp1252'
> ```

No, it has to be set prior to the start of python.

**Comment by s0undt3ch** [comment]
Unless there's some kind of build flag/setting which makes this behavior the default, I'm not seeing relenv taking care of this.

**Comment by dwoz** [comment]
> Unless there's some kind of build flag/setting which makes this behavior the default, I'm not seeing relenv taking care of this.

There's no flag that I am aware of. @twangboy and I have had discussions around this in the past. I think the better approach is to handle this in salt by defaulting to `utf-8` for most things on windows. I would probably be worth us three having a conversation to understand why we needed to add this environment variable in our CI/CD and handle that case. (at least)

**Comment by dwoz** [comment]
This won't be able to be handle by relenv.
