### ISSUE TITLE
Most/all of the bundled libraries are somewhat/significantly out-of-date

### ISSUE THREAD

**Issue by frebib** [saltstack/relative-environment-for-python#75]
Looking through the long list of bundled dependencies, I'm slightly concerned about how old some of the software releases are, especially given that the whole point of this tool is to have zero dependencies. Some are somewhat unimportant/irrelevant, but others like libssl and python are frankly quite important

Looking through the bundled software (for Linux at least; it's the only platform that interests me) here https://github.com/saltstack/relative-environment-for-python/blob/b848c6f7cf7a36587935db349c42e89e0fb0e5b6/relenv/build/linux.py#L353

|Package|Relenv version|Latest version|Notes|
|---|---|---|---|
|glibc|2.17|2.36|This was released 2012-12-25 so is over 10 years old. I don't think there's really any excuse for this one|
|libssl |1.1.1q|3.0.7 (or at least the latest security patch: 1.1.1s)|OpenSSL is security software, so by definition being behind means it's vulnerable. There's also no reason to not use 3.x here; 1.1.x is not going to be supported forever|
|python|3.10.6|3.11.1|3.11 has been out only 13 weeks, but there's strong evidence that it has significant performance gains, especially for Salt in some of the ..less performant parts of the code. I've seen 3.11 drop minutes off some highstate times|
|zlib|1.12.12|1.12.13|1.12.13 fixes a couple of CVEs in 1.12.12. Not critical, but still security related|

From what I can see, this doesn't even have the excuse of "it was latest when we started" because many of these "latest" versions even predate the initial commit of this data: https://github.com/saltstack/relative-environment-for-python/commit/b48d9caac4537ebf9bc6445542ff6924519792c7

I would consider these issues above significant enough to not consider using relenv-based Salt packages until these have been addressed. To me, the whole (and only) reason to go to all of the effort to build what is effectively an isolated system of libraries (like you would in a container) like this is to be able to break away from the grasp of "stable" distributions with old versions and to be able to use new features, bug/security fixes and performance enhancements. Instead, what relenv provides currently is a liability to fork, build and maintain newer versions of libraries to stay secure, but no perceivable benefits for the user

**Comment by dwoz** [comment]
related to #7

**Comment by dwoz** [comment]
@frebib

The glibc version used is the **minimum supported** version. This version of glibc is being used by the toolchain. None of the glibc binaries are shipped with relenv. **Relenv uses the version of glibc available where it's deployed.** We're purposefully using an old glibc version so that relenv will work on older OSes (like centos 7).

**Comment by dwoz** [comment]
Fixed in version 0.7.0
